# Root logger configuration
# Set everything to be logged to the console
#rootLogger.level = INFO
rootLogger.level = OFF
rootLogger.appenderRef.console.ref = console

# Define console appender
appender.console.type = Console
appender.console.name = console
appender.console.target = SYSTEM_OUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yy/MM/dd HH:mm:ss} %p %c{1}: %m%n

# Define Rolling File Appender
# Rolling file configuration
appender.rollingFile.type = RollingFile
appender.rollingFile.name = rollingFile
appender.rollingFile.fileName = app-logs/${sys:logfile.name}.log
appender.rollingFile.filePattern = app-logs/${sys:logfile.name}-%d{yy-MM-dd}.log

#appender.rollingFile.fileName = app-logs/spark-app.log
#appender.rollingFile.filePattern = app-logs/spark-app-%d{yy-MM-dd}.log

appender.rollingFile.layout.type = PatternLayout
appender.rollingFile.layout.pattern = %d{yy/MM/dd HH:mm:ss} %p %c{1}: %m%n
appender.rollingFile.policies.type = Policies
appender.rollingFile.policies.size.type = SizeBasedTriggeringPolicy
appender.rollingFile.policies.size.size = 50MB
appender.rollingFile.strategy.type = DefaultRolloverStrategy
appender.rollingFile.strategy.max = 1

#appender.rollingFile.policies.time.type = TimeBasedTriggeringPolicy
#appender.rollingFile.policies.time.interval = 1
#appender.rollingFile.policies.time.modulate = true

# Define application-specific logger
# Application log for namespace "engineer.studiesproject.spark.example"
logger.engineerStudies.name = engineer.studiesproject.spark.example
#logger.engineerStudies.level = INFO
logger.engineerStudies.level = DEBUG
logger.engineerStudies.appenderRef.console.ref = console
logger.engineerStudies.appenderRef.rollingFile.ref = rollingFile
logger.engineerStudies.additivity = false

# Recommendations from Spark template
# Quiet third-party libraries
logger.sparkReplMain.name = org.apache.spark.repl.Main
#logger.sparkReplMain.level = WARN
logger.sparkReplMain.level = OFF

logger.jetty.name = org.spark_project.jetty
#logger.jetty.level = WARN
logger.jetty.level = OFF

logger.jettyLifeCycle.name = org.spark_project.jetty.util.component.AbstractLifeCycle
#logger.jettyLifeCycle.level = ERROR
logger.jettyLifeCycle.level = OFF

logger.sparkExprTyper.name = org.apache.spark.repl.SparkIMain$exprTyper
#logger.sparkExprTyper.level = INFO
logger.sparkExprTyper.level = OFF

logger.sparkILoop.name = org.apache.spark.repl.SparkILoop$SparkILoopInterpreter
#logger.sparkILoop.level = INFO
logger.sparkILoop.level = OFF

logger.parquet1.name = org.apache.parquet
#logger.parquet1.level = ERROR
logger.parquet1.level = OFF

logger.parquet2.name = parquet
#logger.parquet2.level = ERROR
logger.parquet2.level = OFF

logger.hiveRetryHandler.name = org.apache.hadoop.hive.metastore.RetryingHMSHandler
#logger.hiveRetryHandler.level = FATAL
logger.hiveRetryHandler.level = OFF

logger.functionRegistry.name = org.apache.hadoop.hive.ql.exec.FunctionRegistry
#logger.functionRegistry.level = ERROR
logger.functionRegistry.level = OFF