spark {
    local {
        spark.app.name = "Spark App"
        spark.master = "local[3]"
        spark.author = "Febrianto Kudadiri"
        spark.sql.session.timeZone = "UTC"
    }
}
variables {
    read {
        format = "csv"
        dir = "file:///app/Data/Cars.csv"

    }
    sink {
        format = "csv"
        target = "file:///app/output/result"
    }
}